/**
 * DNS Stack - Route53 Hosted Zones and ACM Certificates
 *
 * This stack provisions Route53 hosted zones and ACM certificates for configured
 * domains. It runs in the shared account to provide centralized DNS management
 * across all stage environments.
 *
 * ## Centralized DNS Management
 *
 * Hosting DNS in a shared account provides several benefits:
 * - Single source of truth for domain configuration
 * - Consistent certificate management across environments
 * - Reduced cost (one hosted zone per domain instead of per environment)
 * - Simplified delegation for stage-specific subdomains
 *
 * ## Wildcard Certificates
 *
 * Each domain gets a wildcard certificate (*.domain.com) to cover all subdomains
 * used by different environments (dev.domain.com, staging.domain.com, etc.).
 * This avoids certificate proliferation and simplifies certificate management.
 *
 * ## Cross-Stack References
 *
 * This stack exports zone IDs and certificate ARNs for use by other stacks:
 * - `{domain-name}-zone-id` (dots replaced with dashes)
 * - `{domain-name}-certificate-arn`
 * @see config/domains.ts - Domain configuration definitions
 * @see lib/types.ts - DomainConfig interface
 * @module lib/stacks/support/dns-stack
 */
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as cdk from "aws-cdk-lib";
import * as route53 from "aws-cdk-lib/aws-route53";
import type { Construct } from "constructs";
import type { DomainConfig } from "../../types";

/**
 * Configuration properties for DnsStack.
 *
 * The domainConfig determines which hosted zones and certificates are created.
 * When domains are empty, this stack creates no resources.
 */
export interface DnsStackProps extends cdk.StackProps {
  /**
   * Domain configuration containing the list of domains to provision.
   * Each domain gets a Route53 hosted zone and ACM wildcard certificate.
   */
  readonly domainConfig: DomainConfig;
}

/**
 * DNS Stack creating Route53 hosted zones and ACM certificates.
 *
 * This stack is deployed to the shared account and creates DNS infrastructure
 * that all stage environments can reference. Each configured domain gets:
 * - A Route53 public hosted zone
 * - An ACM certificate with DNS validation covering apex and wildcard
 *
 * Certificates use DNS validation, which automatically creates the required
 * CNAME records in the hosted zone. This requires the zone to be properly
 * delegated before certificate validation completes.
 */
export class DnsStack extends cdk.Stack {
  /**
   * Sanitizes a domain name into a valid construct ID.
   *
   * Converts domain names (e.g., "example.com") to valid construct IDs
   * (e.g., "Zone-example-com") by replacing dots with dashes.
   * @param domainName - The domain name to sanitize
   * @returns A sanitized construct ID
   */
  private sanitizeConstructId(domainName: string): string {
    return `Zone-${domainName.replace(/\./g, "-")}`;
  }

  /**
   * Map of domain names to their Route53 hosted zones.
   * Use `zones.get("example.com")` to get the hosted zone for a domain.
   */
  public readonly zones: Map<string, route53.HostedZone> = new Map();

  /**
   * Map of domain names to their ACM certificates.
   * Use `certificates.get("example.com")` to get the certificate for a domain.
   */
  public readonly certificates: Map<string, acm.Certificate> = new Map();

  /**
   * Creates a new DnsStack.
   * @param scope - Parent construct
   * @param id - Stack identifier
   * @param props - Stack configuration including domain config
   */
  constructor(scope: Construct, id: string, props: DnsStackProps) {
    super(scope, id, props);

    const { domainConfig } = props;

    domainConfig.domains.forEach(domain => {
      const constructId = this.sanitizeConstructId(domain.name);
      const zone = this.createHostedZone(
        domain.name,
        domain.isPrimary,
        constructId
      );
      const certificate = this.createCertificate(
        domain.name,
        zone,
        constructId
      );

      this.zones.set(domain.name, zone);
      this.certificates.set(domain.name, certificate);

      this.createOutputs(domain.name);
    });
  }

  /**
   * Creates a Route53 hosted zone for a domain.
   *
   * The hosted zone is public and serves as the authoritative DNS for the domain.
   * After creation, the domain registrar must be updated to point to the NS records
   * generated by this zone.
   * @param domainName - The domain name (e.g., "example.com")
   * @param isPrimary - Whether this is the primary domain
   * @param constructId - Stable construct ID derived from domain name
   * @returns The created hosted zone
   */
  private createHostedZone(
    domainName: string,
    isPrimary: boolean,
    constructId: string
  ): route53.HostedZone {
    return new route53.HostedZone(this, constructId, {
      zoneName: domainName,
      comment: `Hosted zone for ${domainName}${isPrimary ? " (primary)" : ""}`,
    });
  }

  /**
   * Creates an ACM certificate with DNS validation.
   *
   * The certificate covers both the apex domain (example.com) and all subdomains
   * (*.example.com). DNS validation is used, which automatically creates CNAME
   * records in the provided hosted zone.
   * @param domainName - The domain name for the certificate
   * @param zone - The hosted zone for DNS validation
   * @param constructId - Stable construct ID derived from domain name
   * @returns The created certificate
   */
  private createCertificate(
    domainName: string,
    zone: route53.HostedZone,
    constructId: string
  ): acm.Certificate {
    return new acm.Certificate(this, `Certificate${constructId}`, {
      domainName,
      subjectAlternativeNames: [`*.${domainName}`],
      validation: acm.CertificateValidation.fromDns(zone),
    });
  }

  /**
   * Creates CloudFormation outputs for cross-stack references.
   *
   * Outputs are named with dots replaced by dashes to comply with CloudFormation
   * naming rules (e.g., "example-com-zone-id" for "example.com").
   * @param domainName - The domain name for output naming
   */
  private createOutputs(domainName: string): void {
    const safeName = domainName.replace(/\./g, "-");
    const zone = this.zones.get(domainName);
    const certificate = this.certificates.get(domainName);

    if (zone) {
      new cdk.CfnOutput(this, `${safeName}-zone-id`, {
        value: zone.hostedZoneId,
        description: `Route53 hosted zone ID for ${domainName}`,
        exportName: `${safeName}-zone-id`,
      });
    }

    if (certificate) {
      new cdk.CfnOutput(this, `${safeName}-certificate-arn`, {
        value: certificate.certificateArn,
        description: `ACM certificate ARN for ${domainName}`,
        exportName: `${safeName}-certificate-arn`,
      });
    }
  }
}
